Settings:
  #Amt of items for each player to find
  Goal-Amount: 5
  #Amount of slots in Bingo Card GUI (Multiple of 9 or it wont work!)
  GUI-Slots: 36
  #Dont spell like a retard plz
  Materials:
    - "ENDER_PEARL"
    - "COOKED_CHICKEN"
    - "BLAZE_ROD"
    - "DIAMOND"
    - "ENDER_EYE"